"""Refactor TestSuite with TestSuiteItem

Revision ID: 31f84607fdbe
Revises: 4c1d33befda0
Create Date: 2025-12-04 15:38:46.956391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '31f84607fdbe'
down_revision: Union[str, Sequence[str], None] = '4c1d33befda0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suite_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.Enum('test_case', 'test_module', 'test_suite', name='suiteitemtype'), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('child_suite_id', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_suite_id'], ['test_suites.id'], ),
    sa.ForeignKeyConstraint(['module_id'], ['test_modules.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suite_items_id'), 'test_suite_items', ['id'], unique=False)
    op.drop_table('test_suite_modules')
    op.drop_table('test_suite_test_cases')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suite_test_cases',
    sa.Column('test_suite_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_case_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], name=op.f('test_suite_test_cases_ibfk_1')),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], name=op.f('test_suite_test_cases_ibfk_2')),
    sa.PrimaryKeyConstraint('test_suite_id', 'test_case_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('test_suite_modules',
    sa.Column('test_suite_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('module_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['test_modules.id'], name=op.f('test_suite_modules_ibfk_1')),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], name=op.f('test_suite_modules_ibfk_2')),
    sa.PrimaryKeyConstraint('test_suite_id', 'module_id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_index(op.f('ix_test_suite_items_id'), table_name='test_suite_items')
    op.drop_table('test_suite_items')
    # ### end Alembic commands ###
