"""Add module field to TestCase

Revision ID: 4c1d33befda0
Revises: f6d488ac7661
Create Date: 2025-12-04 15:34:46.340404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1d33befda0'
down_revision: Union[str, Sequence[str], None] = 'f6d488ac7661'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suites_id'), 'test_suites', ['id'], unique=False)
    op.create_index(op.f('ix_test_suites_name'), 'test_suites', ['name'], unique=False)
    op.create_table('test_suite_modules',
    sa.Column('test_suite_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['test_modules.id'], ),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('test_suite_id', 'module_id')
    )
    op.create_table('test_suite_test_cases',
    sa.Column('test_suite_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.ForeignKeyConstraint(['test_suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('test_suite_id', 'test_case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_suite_test_cases')
    op.drop_table('test_suite_modules')
    op.drop_index(op.f('ix_test_suites_name'), table_name='test_suites')
    op.drop_index(op.f('ix_test_suites_id'), table_name='test_suites')
    op.drop_table('test_suites')
    # ### end Alembic commands ###
