"""Refactor TestSuite with TestSuiteItem

Revision ID: 50572e73a4b6
Revises: 31f84607fdbe
Create Date: 2025-12-04 15:39:50.710651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50572e73a4b6'
down_revision: Union[str, Sequence[str], None] = '31f84607fdbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
