"""add_test_report_tables

Revision ID: 704c588e10fa
Revises: c4009b8ba219
Create Date: 2025-12-08 15:37:53.676190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '704c588e10fa'
down_revision: Union[str, Sequence[str], None] = 'c4009b8ba219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('setup_script', sa.String(length=5000), nullable=True))
    op.add_column('test_cases', sa.Column('teardown_script', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_cases', 'teardown_script')
    op.drop_column('test_cases', 'setup_script')
    # ### end Alembic commands ###
