"""add script fields to testcase

Revision ID: 7a3d922c10fb
Revises: 704c588e10fa
Create Date: 2025-12-08 16:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision: str = '7a3d922c10fb'
down_revision: Union[str, Sequence[str], None] = '704c588e10fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Get database connection
    conn = op.get_bind()
    # Create inspector
    inspector = sa.inspect(conn)
    # Get existing columns in test_cases table
    columns = [x['name'] for x in inspector.get_columns('test_cases')]
    
    # ### commands auto generated by Alembic - please adjust! ###
    if 'setup_script' not in columns:
        op.add_column('test_cases', sa.Column('setup_script', sa.Text(), nullable=True))
    
    if 'teardown_script' not in columns:
        op.add_column('test_cases', sa.Column('teardown_script', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Get database connection
    conn = op.get_bind()
    # Create inspector
    inspector = sa.inspect(conn)
    # Get existing columns in test_cases table
    columns = [x['name'] for x in inspector.get_columns('test_cases')]

    # ### commands auto generated by Alembic - please adjust! ###
    if 'teardown_script' in columns:
        op.drop_column('test_cases', 'teardown_script')
    if 'setup_script' in columns:
        op.drop_column('test_cases', 'setup_script')
    # ### end Alembic commands ###