"""Add module field to TestCase

Revision ID: 99f32351434d
Revises: c6ac119d2988
Create Date: 2025-12-04 13:59:34.770464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99f32351434d'
down_revision: Union[str, Sequence[str], None] = 'c6ac119d2988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('priority', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_test_cases_priority'), 'test_cases', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_priority'), table_name='test_cases')
    op.drop_column('test_cases', 'priority')
    # ### end Alembic commands ###
