"""Add module field to TestCase

Revision ID: a9634aaf451e
Revises: 9d553b09c7f0
Create Date: 2025-12-04 13:57:19.097964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a9634aaf451e'
down_revision: Union[str, Sequence[str], None] = '9d553b09c7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('module', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_test_cases_priority'), table_name='test_cases')
    op.create_index(op.f('ix_test_cases_module'), 'test_cases', ['module'], unique=False)
    op.drop_column('test_cases', 'priority')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_cases', sa.Column('priority', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_test_cases_module'), table_name='test_cases')
    op.create_index(op.f('ix_test_cases_priority'), 'test_cases', ['priority'], unique=False)
    op.drop_column('test_cases', 'module')
    # ### end Alembic commands ###
