"""add_test_report_tables

Revision ID: c4009b8ba219
Revises: 50572e73a4b6
Create Date: 2025-12-04 18:06:26.007050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

# revision identifiers, used by Alembic.
revision: str = 'c4009b8ba219'
down_revision: Union[str, Sequence[str], None] = '50572e73a4b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除可能存在的表，处理之前的失败残留
    op.execute("DROP TABLE IF EXISTS test_records")
    op.execute("DROP TABLE IF EXISTS test_reports")
    
    op.create_table('test_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('suite_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('total_cases', sa.Integer(), nullable=True),
    sa.Column('pass_count', sa.Integer(), nullable=True),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_reports_id'), 'test_reports', ['id'], unique=False)
    op.create_table('test_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('test_case_id', sa.Integer(), nullable=True),
    sa.Column('case_name', sa.String(length=100), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('request_headers', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('request_body', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('response_headers', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('assertion_results', postgresql.JSON(astext_type=Text()), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['test_reports.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_records_id'), 'test_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_records_id'), table_name='test_records')
    op.drop_table('test_records')
    op.drop_index(op.f('ix_test_reports_id'), table_name='test_reports')
    op.drop_table('test_reports')
    # ### end Alembic commands ###