"""Add test_modules table and update test_cases

Revision ID: d0623e6416d3
Revises: 99f32351434d
Create Date: 2025-12-04 14:22:22.089816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0623e6416d3'
down_revision: Union[str, Sequence[str], None] = '99f32351434d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['test_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_modules_id'), 'test_modules', ['id'], unique=False)
    op.create_index(op.f('ix_test_modules_name'), 'test_modules', ['name'], unique=False)
    op.add_column('test_cases', sa.Column('module_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'test_cases', 'test_modules', ['module_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_column('test_cases', 'module_id')
    op.drop_index(op.f('ix_test_modules_name'), table_name='test_modules')
    op.drop_index(op.f('ix_test_modules_id'), table_name='test_modules')
    op.drop_table('test_modules')
    # ### end Alembic commands ###
